sensors:
  - name: "bosch pst-ft-2 (temperature)"
    x_values: [45303, 26108, 15458, 9395, 5895, 3791, 2499, 2056, 1706, 1174, 833.8, 595.4, 435.6, 322.5, 243.1, 186.6, 144.2, 112.7, 89.28]
    y_values: [-40, -30, -20, -10, 0, 10, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130]
    can_id: 0xb003
    can_data_offset: 0
    can_data_width: 2
    x_index: 0
    y_index: 0
    z_index: 0
    id: 0

  - name: "delphi 25036751 (temperature)"
    x_values: [52.6, 59.4, 67.3, 76.4, 87, 99.4, 113.9, 131, 151.3, 175.3, 203.9, 238.1, 279, 329, 389, 462, 551, 660, 796, 965, 1177, 1443, 1778, 2205, 2752, 3457, 4373, 5572, 7153, 9256, 12073, 15873, 21044, 28146, 37994, 51791, 71332, 99326]
    y_values: [145, 140, 135, 130, 125, 120, 115, 110, 105, 100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0, -5, -10, -15, -20, -25, -30, -35, -40]
    can_id: 0xb003
    can_data_offset: 2
    can_data_width: 2
    x_index: 1
    y_index: 0
    z_index: 0
    id: 1

  - name: "aem 30-2011 (temperature)"
    x_values: [100000, 29000, 9800, 3700, 1500, 500, 180]
    y_values: [-40, -20, 0, 20, 40, 70, 100]
    can_id: 0xb003
    can_data_offset: 4
    can_data_width: 2
    x_index: 2
    y_index: 0
    z_index: 0
    id: 2

  - name: "bosch pst-ft (pressure)"
    x_values: [0, 500, 4500]
    y_values: [-1.25, 0, 10]
    can_id: 0xb000
    can_data_offset: 0
    can_data_width: 2
    x_index: 0
    y_index: 1
    z_index: 0
    id: 3

  - name: "bosch pst-ft (pressure)"
    x_values: [0, 500, 4500]
    y_values: [-1.25, 0, 10]
    can_id: 0xb000
    can_data_offset: 2
    can_data_width: 2
    x_index: 1
    y_index: 1
    z_index: 0
    id: 4

  - name: "TPMS multiplexor channel"
    can_id: 0x77e
    can_data_offset: 0
    can_data_width: 1
    x_index: 2
    y_index: 1
    z_index: 0
    id: 5

  - name: "TMPS pressure channel"
    can_id: 0x77e
    can_data_offset: 1
    can_data_width: 2
    x_index: 2
    y_index: 1
    z_index: 0
    scale: 0.001000
    id: 5

  - name: "TMPS temperature channel"
    can_id: 0x77e
    can_data_offset: 3
    can_data_width: 1
    x_index: 2
    y_index: 1
    z_index: 0
    id: 5

  - name: "TMPS voltage channel"
    can_id: 0x77e
    can_data_offset: 4
    can_data_width: 1
    x_index: 2
    y_index: 1
    z_index: 0
    id: 5

  - name: "Haltech (and others) TPMS"
    can_id: 0x777
    can_data_offset: 4
    can_data_width: 1
    x_index: 2
    y_index: 1
    z_index: 0
    id: 5


panels:
  - type: radial_temperature
    label: "Water"
    x_index: 0
    y_index: 0
    z_index: 0
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 0
    min_value: 0.000
    max_value: 120.000
    low_warn : -27.000
    high_warn: 105.000
    units: "°F"
    output_format: "%.0f"

  - type: radial_temperature
    label: "Water"
    x_index: 0
    y_index: 0
    z_index: 1
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 0
    min_value: 0.000
    max_value: 120.000
    low_warn : -27.000
    high_warn: 105.000
    units: "°C"
    output_format: "%.0f"

  - type: radial_temperature
    label: "Intake"
    x_index: 1
    y_index: 0
    z_index: 1
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 1
    min_value: -40.000
    max_value: 65.000
    low_warn : 0.000
    high_warn: 70.000
    units: "°C"
    output_format: "%.0f"

  - type: radial_temperature
    label: "Intake"
    x_index: 1
    y_index: 0
    z_index: 0
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 1
    min_value: 0.000
    max_value: 130.000
    low_warn : -10.000
    high_warn: 110.000
    units: "°F"
    output_format: "%.0f"

  - type: linear_temperature
    label: "Oil"
    x_index: 2
    y_index: 0
    z_index: 0
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 2
    min_value: -1.000
    max_value: 220.000
    low_warn : 60.000
    high_warn: 180.000
    units: "°F"
    output_format: "%.0f"

  - type: linear_temperature
    label: "Oil"
    x_index: 2
    y_index: 0
    z_index: 1
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 2
    min_value: -1.000
    max_value: 105.000
    low_warn : 16.000
    high_warn: 82.000
    units: "°C"
    output_format: "%.0f"

  - type: radial_temperature
    label: "Oil"
    x_index: 2
    y_index: 0
    z_index: 2
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 2
    min_value: -1.000
    max_value: 220.000
    low_warn : 60.000
    high_warn: 180.000
    units: "°F"
    output_format: "%.0f"

  - type: radial_pressure
    label: "Oil"
    x_index: 0
    y_index: 1
    z_index: 0
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 3
    min_value: 0.000
    max_value: 8.000
    low_warn : 3.000
    high_warn: 5.500
    units: "bar"
    output_format: "%.0f"

  - type: radial_pressure
    label: "Oil"
    x_index: 0
    y_index: 1
    z_index: 1
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 3
    min_value: 0.000
    max_value: 250.000
    low_warn : 40.000
    high_warn: 180.000
    units: "psi"
    output_format: "%.0f"

  - type: radial_pressure
    label: "MAP"
    x_index: 1
    y_index: 1
    z_index: 0
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 4
    min_value: 1.000
    max_value: 4.000
    low_warn : 1.500
    high_warn: 3.500
    units: "bar"
    output_format: "%.0f"

  - type: radial_pressure
    label: "MAP"
    x_index: 1
    y_index: 1
    z_index: 1
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 4
    min_value: -101.000
    max_value: 100.000
    low_warn : -1000.000
    high_warn: 1000.000
    units: "kPa"
    output_format: "%.1f"

  - type: radial_pressure
    label: "MAP"
    x_index: 1
    y_index: 1
    z_index: 2
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 0
    id: 4
    min_value: 1.000
    max_value: 4.000
    low_warn : 1.500
    high_warn: 3.500
    units: "bar"
    output_format: "%.2f"

  - type: tpms
    x_index: 2
    y_index: 1
    z_index: 0
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 1500
    id: 5
    min_value: 0.000
    max_value: 0.000
    low_warn : 30.000
    high_warn: 150.000
    units: "°F"
    output_format: "%.0f"
    pressure_units: "bar"
    temperature_units: "°C"

  - type: tpms
    x_index: 2
    y_index: 1
    z_index: 1
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 1500
    id: 5
    min_value: 0.000
    max_value: 0.000
    low_warn : 30.000
    high_warn: 150.000
    units: "°F"
    output_format: "%.0f"
    pressure_units: "psi"
    temperature_units: "°F"

  - type: info
    x_index: 2
    y_index: 1
    z_index: 2
    border: 1
    foreground_color: 0xffa600
    background_color: 0x0
    high_warn_color: 0xff0808
    low_warn_color: 0xe0e0e0
    timeout: 1500
    id: 5
    
